### ISSUE TITLE
gcc versions later than 6 are not supported

### ISSUE THREAD

**Issue by mdhimes** [ComputationalRadiationPhysics/cuda_memtest#26]
Hello,

When trying to build the software via make, I get the following error:
In file included from /usr/include/host_config.h:50:0,
                 from /usr/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!

Any plans to update the software to be compatible with gcc versions > 6?

**Comment by sbastrakov** [comment]
Hello @mdhimes . This limitation might come not from our build scripts, but from your CUDA version, perhaps it is < 9.1.85 ? At least, according to [our experience](https://gist.github.com/ax3l/9489132) gcc > 6 is not compatible with earlier CUDA versions.

**Comment by mdhimes** [comment]
Thanks for the prompt response.  I am using a Titan Xp, so it's certainly possible that I do have CUDA version < 9.1.85.  I will check this once I am able to do so.  I am currently running memtest on the machine to rule out issues with the RAM, and will check the GPU RAM after.

**Comment by ax3l** [comment]
Thanks for your report and thank you for using `cuda_memtest`.

Yes, so this is not a problem with `cuda_memtest` but with your local setup.
You can either proceed by:
- [Using and older host compiler](https://devtalk.nvidia.com/default/topic/1037428/ubuntu-18-04-nvcc-can-t-find-appropriate-host-compiler/), e.g. via `nvcc -ccbin <path/to/compiler> something.cu` or `export CXX=$(which g++-5); export CC=$(which gcc-5)` before CMake, or by
- [upgrading your CUDA drivers and Toolkit](https://developer.nvidia.com/cuda-downloads) to CUDA 9.2 or newer, which [as linked above](https://gist.github.com/ax3l/9489132) works well with newer GCC releases and therefore this project.

CUDA/NVCC host-compiler restrictions are set by Nvidia and we do not have influence on that. Basically, it's usually the compiler versions that were available on a CUDA release, so Nvidia could adopt for and test against those.
