### ISSUE TITLE
"Missing separator . Stop." in generated Makefiles

### ISSUE THREAD

**Issue by superbob** [ComputationalRadiationPhysics/cuda_memtest#27]
I'm on Windows 10, using [_Windows win64-x64 CMake_](https://cmake.org/download/) (cmake-3.17.1-win64-x64.msi), [_GnuWin make_](http://gnuwin32.sourceforge.net/packages/make.htm) and [_Visual Studio 2019 Build Tools_](https://visualstudio.microsoft.com/fr/downloads/) (C++ compiler only).
I'm having issues in generated Makefiles:

**Main Makefile**
```
>"C:\Program Files (x86)\GnuWin32\bin\make.exe"
makefile:40: *** missing sepator . Stop.
```
**CMakeFiles/Makefile2**
```
>"C:\Program Files (x86)\GnuWin32\bin\make.exe"
CMakeFiles\Makefile2:36: *** missing sepator . Stop.
make: *** [all] Error 2
```
In both cases, the problem occurs at these lines:
```
!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
```
The error occurs at the `!ELSE` line.
I've commented all the lines but the `NULL=`  and the compilation continues, but I have other errors. I don't know if it is related.
I'm opening another issue for the other error I'm encountering now.

**Comment by superbob** [comment]
Ok, I've tried to regenerate the project, and it doesn't generate Makefile anymore, it generate a MS Solution now :/.
There are `CUDA_memtest.sln` and `.vcxproj `files generated now.
The issue can be closed now as I don't reproduce the problem now.

**Comment by psychocoderHPC** [comment]
Please post all command you used so that we can reproduce the issue.

Update: I missed that you solved the issue already

Am 11. April 2020 12:25:57 MESZ schrieb Florian Morgan <notifications@github.com>:

**Comment by superbob** [comment]
Just for the record, I gave up compiling on Windows it is too difficult.
What I tried:

1. Compile using MS toolchain (Visual Studio Build Tools, free SDK).
    => Install CMake for Windows and run cmake on the Visual Studio Tools command line shell.
    Doesn't work because of missing POSIX headers (at least, pthread, sys/date)
2. Compile using MSYS2 (Cygwin/MinGW) toolchain.
    => Install CMake, GNU tools through package manager (pacman) and run cmake on the MSYS2 command line shell.
    Doesn't work because CUDA SDK doesn't work on Windows with Cygwin/MinGW toolchain)

I don't have enough time to spend on this so I'm giving up, but it could have been nice to be able to build on Windows.
